---
compact: true
directory:
  - .
skip-path:
  - tests
skip-check:
  - CKV_K8S_10 # CPU requests should be set
  - CKV_K8S_11 # CPU limits should be set
  - CKV_K8S_12 # Memory requests should be set
  - CKV_K8S_13 # Memory limits should be set
  - CKV_K8S_14 # Image Tag should be fixed - not latest or blank
  - CKV_K8S_20 # Containers should not run with allowPrivilegeEscalation
  - CKV_K8S_22 # Use read-only filesystem for containers where possible
  - CKV_K8S_23 # Minimize the admission of root containers
  - CKV_K8S_28 # Minimize the admission of containers with the NET_RAW capability
  - CKV_K8S_29 # Apply security context to your pods and containers
  - CKV_K8S_30 # Apply security context to your containers
  - CKV_K8S_31 # Ensure that the seccomp profile is set to docker/default or runtime/default
  - CKV_K8S_37 # Minimize the admission of containers with capabilities assigned
  - CKV_K8S_38 # Ensure that Service Account Tokens are only mounted where necessary
  - CKV_K8S_40 # Containers should run as a high UID to avoid host conflict
  - CKV_K8S_43 # Image should use digest
